USE trouve_ton_artisan;

INSERT INTO categories (name, slug, description) VALUES
  ('Bâtiment', 'batiment', 'Professionnels du gros œuvre, second œuvre et rénovation énergétique.'),
  ('Services', 'services', 'Artisans au service des particuliers pour l''entretien et le bien-être.'),
  ('Fabrication', 'fabrication', 'Savoir-faire locaux pour la conception et la fabrication d''objets.'),
  ('Alimentation', 'alimentation', 'Artisans de bouche et producteurs locaux.');

INSERT INTO specialties (name, slug, description, category_id) VALUES
  ('Charpente & couverture', 'charpente-couverture', 'Construction et rénovation de toitures en bois.', 1),
  ('Plomberie écoresponsable', 'plomberie-ecoresponsable', 'Installation de solutions hydro-économes.', 1),
  ('Rénovation énergétique', 'renovation-energetique', 'Isolation et amélioration thermique de l''habitat.', 1),
  ('Soutien à domicile', 'soutien-domicile', 'Services d''aide et d''accompagnement aux personnes.', 2),
  ('Entretien paysager', 'entretien-paysager', 'Création et entretien d''espaces verts.', 2),
  ('Réparation numérique', 'reparation-numerique', 'Maintenance d''appareils électroniques.', 2),
  ('Ébénisterie', 'ebenisterie', 'Conception de mobilier sur mesure.', 3),
  ('Céramique artisanale', 'ceramique-artisanale', 'Création de pièces uniques en céramique.', 3),
  ('Textile durable', 'textile-durable', 'Ateliers de confection respectueux de l''environnement.', 3),
  ('Boulangerie bio', 'boulangerie-bio', 'Fabrication de pains et viennoiseries bio.', 4),
  ('Fromagerie fermière', 'fromagerie-fermiere', 'Production de fromages fermiers locaux.', 4),
  ('Chocolaterie artisanale', 'chocolaterie-artisanale', 'Créations chocolatières locales.', 4);

INSERT INTO artisans
  (name, slug, email, phone, rating, short_description, description, city, department, service_area, cover_image_url, website, highlighted, specialty_id)
VALUES
  ('Charpentes du Vercors', 'charpentes-du-vercors', 'contact@charpentes-vercors.fr', '+33 4 76 00 00 01', 4.8,
   'Charpentiers éco-responsables au cœur du Vercors.',
   'Spécialistes des charpentes traditionnelles en bois local certifié PEFC, nous accompagnons les projets de construction et de rénovation.',
   'Villard-de-Lans', '38', 'Isère, Drôme', 'https://images.unsplash.com/photo-1503389152951-9f343605f61e?auto=format&fit=crop&w=1200&q=80',
   'https://charpentes-vercors.fr', 1, 1),
  ('Plombiers des Alpes', 'plombiers-des-alpes', 'hello@plombiers-des-alpes.fr', '+33 4 76 00 00 02', 4.6,
   'Installation de solutions hydro-économes et entretien.',
   'Équipe certifiée RGE pour l''installation de systèmes économes en eau et en énergie, adaptée aux logements anciens et récents.',
   'Grenoble', '38', 'Grenoble-Alpes Métropole', 'https://images.unsplash.com/photo-1523419409543-0c1df022bdd1?auto=format&fit=crop&w=1200&q=80',
   'https://plombiers-des-alpes.fr', 1, 2),
  ('Isol''&Co', 'isol-et-co', 'contact@isol-co.fr', '+33 4 73 00 00 03', 4.9,
   'Experts en rénovation énergétique globale.',
   'Audit énergétique, isolation biosourcée et installation de pompes à chaleur pour les habitations en montagne.',
   'Clermont-Ferrand', '63', 'Puy-de-Dôme et Allier', 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1200&q=80',
   'https://isol-co.fr', 1, 3),
  ('Maison Harmonie', 'maison-harmonie', 'contact@maison-harmonie.fr', '+33 4 50 00 00 04', 4.7,
   'Aide à domicile personnalisée et attentive.',
   'Accompagnement quotidien des seniors : organisation des sorties, coordination médicale et prestations de confort.',
   'Annecy', '74', 'Haute-Savoie', 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1200&q=80',
   'https://maison-harmonie.fr', 0, 4),
  ('Montagne Verte Paysage', 'montagne-verte-paysage', 'contact@montagneverte.fr', '+33 4 50 00 00 05', 4.5,
   'Création et entretien écologique de jardins alpins.',
   'Paysagistes passionnés par la biodiversité locale, nous créons des jardins résilients adaptés au climat de montagne.',
   'Chamonix', '74', 'Vallée de Chamonix', 'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1200&q=80',
   'https://montagneverte-paysage.fr', 0, 5),
  ('Atelier PixiTech', 'atelier-pixitech', 'contact@pixitech.fr', '+33 4 72 00 00 06', 4.4,
   'Réparation express de vos appareils numériques.',
   'Réparations garanties et recyclage des composants dans une démarche zéro déchet.',
   'Lyon', '69', 'Métropole de Lyon', 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
   'https://atelier-pixitech.fr', 0, 6),
  ('Atelier Bois & Montagne', 'atelier-bois-montagne', 'bonjour@bois-montagne.fr', '+33 4 79 00 00 07', 4.9,
   'Mobilier sur mesure en bois local.',
   'Création de mobilier durable inspiré des reliefs alpins, finitions naturelles et livraison dans toute la région.',
   'Chambéry', '73', 'Savoie et Haute-Savoie', 'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1200&q=80',
   'https://atelier-bois-montagne.fr', 1, 7),
  ('Terres & Flammes', 'terres-et-flammes', 'contact@terresetflammes.fr', '+33 4 75 00 00 08', 4.3,
   'Pièces de céramique artisanale inspirées des volcans.',
   'Atelier labellisé « Artisan d''art » avec boutique en ligne et ateliers découvertes.',
   'Le Puy-en-Velay', '43', 'Haute-Loire', 'https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=1200&q=80',
   'https://terresetflammes.fr', 0, 8),
  ('Loom Local', 'loom-local', 'hello@loomlocal.fr', '+33 4 26 00 00 09', 4.6,
   'Atelier textile durable et inclusif.',
   'Production de séries limitées à partir de fibres recyclées et formations à la réparation textile.',
   'Saint-Étienne', '42', 'Loire et Rhône', 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=1200&q=80',
   'https://loomlocal.fr', 0, 9),
  ('Grain d''Or Bio', 'grain-d-or-bio', 'bonjour@graindorbio.fr', '+33 4 78 00 00 10', 4.8,
   'Boulangerie bio engagée, levain naturel.',
   'Pain au levain cuit au feu de bois, farine issue de moulins régionaux et offre de boulangerie inclusive.',
   'Villeurbanne', '69', 'Lyon Métropole', 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1200&q=80',
   'https://graindorbio.fr', 1, 10),
  ('La Ferme des Aravis', 'la-ferme-des-aravis', 'contact@ferme-des-aravis.fr', '+33 4 50 00 00 11', 4.7,
   'Fromages fermiers AOP et visites pédagogiques.',
   'Exploitation familiale en agriculture raisonnée, propose des ateliers de découverte pour tous les publics.',
   'Thônes', '74', 'Haute-Savoie', 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?auto=format&fit=crop&w=1200&q=80',
   'https://ferme-des-aravis.fr', 0, 11),
  ('ChocoLyon', 'chocolyon', 'bonjour@chocolyon.fr', '+33 4 72 00 00 12', 4.9,
   'Chocolaterie bean-to-bar à Lyon.',
   'Tablettes grand cru, créations végétales et ateliers sensoriels accessibles aux publics en situation de handicap.',
   'Lyon', '69', 'Métropole de Lyon', 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=1200&q=80',
   'https://chocolyon.fr', 1, 12);
